import { useEffect, useMemo, useState } from 'react';
import CSS from './styles.js';

const STRATEGIES = {
  balanced: { label: 'Balanced Mix', minLen: 3, maxLen: 10, minGap: 14 },
  longWeekends: { label: 'Long Weekends', minLen: 3, maxLen: 4, minGap: 7 },
  miniBreaks: { label: 'Mini Breaks', minLen: 5, maxLen: 6, minGap: 12 },
  weekLong: { label: 'Week-long Breaks', minLen: 7, maxLen: 9, minGap: 18 },
  extended: { label: 'Extended Vacations', minLen: 10, maxLen: 15, minGap: 28 },
};

const HOLIDAY_PRESETS_US_2026 = [
  '2026-01-01', '2026-01-19', '2026-02-16', '2026-05-25', '2026-06-19',
  '2026-07-03', '2026-09-07', '2026-10-12', '2026-11-11', '2026-11-26', '2026-12-25',
];

const HOLIDAY_PRESETS_US_2027 = [
  '2027-01-01', '2027-01-18', '2027-02-15', '2027-05-31', '2027-06-18',
  '2027-07-05', '2027-09-06', '2027-10-11', '2027-11-11', '2027-11-25', '2027-12-24',
];

const STORAGE_KEY = 'ptoOptimizerScenario_v1';

function formatISO(date) {
  return date.toISOString().slice(0, 10);
}

function parseISO(value) {
  return new Date(`${value}T00:00:00`);
}

function addDays(date, days) {
  const copy = new Date(date);
  copy.setDate(copy.getDate() + days);
  return copy;
}

function toIcsDate(value) {
  return value.replaceAll('-', '');
}

function buildIcs(planName, breaks) {
  const stamp = new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//PTO Optimizer//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
  ];

  breaks.forEach((b, idx) => {
    lines.push('BEGIN:VEVENT');
    lines.push(`UID:pto-optimizer-${idx}-${b.start}`);
    lines.push(`DTSTAMP:${stamp}Z`);
    lines.push(`DTSTART;VALUE=DATE:${toIcsDate(b.start)}`);
    lines.push(`DTEND;VALUE=DATE:${toIcsDate(b.endExclusive)}`);
    lines.push(`SUMMARY:${planName} · ${b.daysOff} day break`);
    lines.push(`DESCRIPTION:PTO used: ${b.ptoDays.length}. Auto-generated by PTO Optimizer clone.`);
    lines.push('END:VEVENT');
  });

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

function download(filename, content, type = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function getTimeframe(timeframe, rollingStartMonth, rollingStartYear) {
  if (timeframe === '2026') return { start: '2026-01-01', end: '2026-12-31' };
  if (timeframe === '2027') return { start: '2027-01-01', end: '2027-12-31' };
  const start = new Date(Date.UTC(Number(rollingStartYear), Number(rollingStartMonth), 1));
  const end = new Date(Date.UTC(start.getUTCFullYear() + 1, start.getUTCMonth(), 0));
  return { start: formatISO(start), end: formatISO(end) };
}

function buildDayIndex(startISO, endISO) {
  const list = [];
  let cursor = parseISO(startISO);
  const end = parseISO(endISO);
  while (cursor <= end) {
    list.push(formatISO(cursor));
    cursor = addDays(cursor, 1);
  }
  return list;
}

function optimizePlan({ ptoDays, timeframe, strategyKey, weekendDays, holidays, prebooked, companyDays, rollingStartMonth, rollingStartYear }) {
  const strategy = STRATEGIES[strategyKey];
  const { start, end } = getTimeframe(timeframe, rollingStartMonth, rollingStartYear);
  const dayIndex = buildDayIndex(start, end);
  const dayToIdx = new Map(dayIndex.map((d, idx) => [d, idx]));

  const weekendSet = new Set(weekendDays);
  const holidaySet = new Set(holidays);
  const prebookSet = new Set(prebooked);
  const companySet = new Set(companyDays);

  const isFreeDay = (dateISO) => {
    const date = parseISO(dateISO);
    const weekday = date.getDay();
    return weekendSet.has(weekday) || holidaySet.has(dateISO) || prebookSet.has(dateISO) || companySet.has(dateISO);
  };

  const prefixPtoCost = [0];
  dayIndex.forEach((d, i) => {
    const cost = isFreeDay(d) ? 0 : 1;
    prefixPtoCost[i + 1] = prefixPtoCost[i] + cost;
  });

  const candidates = [];
  for (let i = 0; i < dayIndex.length; i += 1) {
    for (let len = strategy.minLen; len <= strategy.maxLen; len += 1) {
      const j = i + len - 1;
      if (j >= dayIndex.length) continue;
      const pto = prefixPtoCost[j + 1] - prefixPtoCost[i];
      if (pto <= 0 || pto > ptoDays) continue;
      const freeCount = len - pto;
      candidates.push({
        startIdx: i,
        endIdx: j,
        score: len * 100 + freeCount * 14 - pto * 10,
      });
    }
  }

  candidates.sort((a, b) => b.score - a.score || a.startIdx - b.startIdx);

  let remaining = ptoDays;
  const chosen = [];

  for (const c of candidates) {
    if (remaining <= 0) break;
    const overlaps = chosen.some((ch) => c.startIdx <= ch.endIdx && c.endIdx >= ch.startIdx);
    if (overlaps) continue;

    const tooClose = chosen.some((ch) => {
      const gap = c.startIdx > ch.endIdx ? c.startIdx - ch.endIdx - 1 : ch.startIdx - c.endIdx - 1;
      return gap < strategy.minGap;
    });
    if (tooClose) continue;

    const cost = prefixPtoCost[c.endIdx + 1] - prefixPtoCost[c.startIdx];
    if (cost > remaining) continue;

    chosen.push({ ...c, ptoCost: cost });
    remaining -= cost;
  }

  chosen.sort((a, b) => a.startIdx - b.startIdx);

  const breaks = chosen.map((c) => {
    const ptoDaysInBreak = [];
    for (let i = c.startIdx; i <= c.endIdx; i += 1) {
      const d = dayIndex[i];
      if (!isFreeDay(d)) ptoDaysInBreak.push(d);
    }
    return {
      start: dayIndex[c.startIdx],
      end: dayIndex[c.endIdx],
      endExclusive: formatISO(addDays(parseISO(dayIndex[c.endIdx]), 1)),
      daysOff: c.endIdx - c.startIdx + 1,
      ptoDays: ptoDaysInBreak,
    };
  });

  return {
    start,
    end,
    breaks,
    ptoUsed: ptoDays - remaining,
    ptoRemaining: remaining,
    totalDaysOff: breaks.reduce((sum, b) => sum + b.daysOff, 0),
  };
}

function addUnique(dateValue, current, setter) {
  if (!dateValue) return;
  const set = new Set(current);
  set.add(dateValue);
  setter([...set].sort());
}

export default function App() {
  const [ptoDays, setPtoDays] = useState(18);
  const [timeframe, setTimeframe] = useState('2026');
  const [strategyKey, setStrategyKey] = useState('balanced');
  const [weekendDays, setWeekendDays] = useState([0, 6]);
  const [holidays, setHolidays] = useState(HOLIDAY_PRESETS_US_2026);
  const [prebooked, setPrebooked] = useState([]);
  const [companyDays, setCompanyDays] = useState([]);
  const [rollingStartMonth, setRollingStartMonth] = useState(0);
  const [rollingStartYear, setRollingStartYear] = useState(2026);
  const [newDate, setNewDate] = useState('');
  const [scenarioSnapshots, setScenarioSnapshots] = useState([]);

  useEffect(() => {
    const style = document.createElement('style');
    style.textContent = CSS;
    document.head.appendChild(style);
    return () => style.remove();
  }, []);

  useEffect(() => {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return;
    try {
      const parsed = JSON.parse(raw);
      setScenarioSnapshots(Array.isArray(parsed) ? parsed : []);
    } catch {
      setScenarioSnapshots([]);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(scenarioSnapshots));
  }, [scenarioSnapshots]);

  useEffect(() => {
    setHolidays(timeframe === '2027' ? HOLIDAY_PRESETS_US_2027 : HOLIDAY_PRESETS_US_2026);
  }, [timeframe]);

  const result = useMemo(() => optimizePlan({
    ptoDays,
    timeframe,
    strategyKey,
    weekendDays,
    holidays,
    prebooked,
    companyDays,
    rollingStartMonth,
    rollingStartYear,
  }), [ptoDays, timeframe, strategyKey, weekendDays, holidays, prebooked, companyDays, rollingStartMonth, rollingStartYear]);

  const toggleWeekend = (dayIdx) => {
    setWeekendDays((current) => {
      if (current.includes(dayIdx)) return current.length === 1 ? current : current.filter((d) => d !== dayIdx);
      return [...current, dayIdx].sort();
    });
  };

  const saveScenario = () => {
    const snapshot = {
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      label: `${new Date().toLocaleDateString()} · ${STRATEGIES[strategyKey].label}`,
      state: { ptoDays, timeframe, strategyKey, weekendDays, holidays, prebooked, companyDays, rollingStartMonth, rollingStartYear },
    };
    setScenarioSnapshots((s) => [snapshot, ...s].slice(0, 8));
  };

  const duplicateScenario = (snapshot) => {
    const dupe = {
      ...snapshot,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      label: `${snapshot.label} (Copy)`,
    };
    setScenarioSnapshots((s) => [dupe, ...s].slice(0, 8));
    Object.entries(dupe.state).forEach(([k, v]) => {
      if (k === 'ptoDays') setPtoDays(v);
      if (k === 'timeframe') setTimeframe(v);
      if (k === 'strategyKey') setStrategyKey(v);
      if (k === 'weekendDays') setWeekendDays(v);
      if (k === 'holidays') setHolidays(v);
      if (k === 'prebooked') setPrebooked(v);
      if (k === 'companyDays') setCompanyDays(v);
      if (k === 'rollingStartMonth') setRollingStartMonth(v);
      if (k === 'rollingStartYear') setRollingStartYear(v);
    });
  };

  const exportPlanIcs = () => {
    const ics = buildIcs('PTO Optimization Plan', result.breaks);
    download('pto-optimized-plan.ics', ics, 'text/calendar;charset=utf-8');
  };

  const exportJson = () => {
    download('pto-plan.json', JSON.stringify({ generatedAt: new Date().toISOString(), input: { ptoDays, timeframe, strategyKey, weekendDays, holidays, prebooked, companyDays }, result }, null, 2), 'application/json;charset=utf-8');
  };

  return (
    <div className="page">
      <header className="hero">
        <h1>PTO Optimizer Studio</h1>
        <p>Holiday itemizer clone: maximize PTO, stretch breaks, duplicate scenarios, and auto-add your plan to calendar.</p>
      </header>

      <main className="layout">
        <section className="panel">
          <h2>Optimization Inputs</h2>
          <label>
            PTO days
            <input type="number" min="0" max="80" value={ptoDays} onChange={(e) => setPtoDays(Number(e.target.value))} />
          </label>

          <label>
            Timeframe
            <select value={timeframe} onChange={(e) => setTimeframe(e.target.value)}>
              <option value="2026">Calendar Year 2026</option>
              <option value="2027">Calendar Year 2027</option>
              <option value="rolling12">Rolling 12-Month Period</option>
            </select>
          </label>

          {timeframe === 'rolling12' && (
            <div className="inline-grid">
              <label>
                Start month
                <select value={rollingStartMonth} onChange={(e) => setRollingStartMonth(Number(e.target.value))}>
                  {Array.from({ length: 12 }).map((_, i) => <option key={i} value={i}>{new Date(2026, i, 1).toLocaleString(undefined, { month: 'long' })}</option>)}
                </select>
              </label>
              <label>
                Start year
                <input type="number" value={rollingStartYear} onChange={(e) => setRollingStartYear(Number(e.target.value))} />
              </label>
            </div>
          )}

          <label>
            Strategy
            <select value={strategyKey} onChange={(e) => setStrategyKey(e.target.value)}>
              {Object.entries(STRATEGIES).map(([k, s]) => <option key={k} value={k}>{s.label}</option>)}
            </select>
          </label>

          <div>
            <div className="mini-title">Custom weekends</div>
            <div className="chips">
              {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day, idx) => (
                <button key={day} className={weekendDays.includes(idx) ? 'chip active' : 'chip'} onClick={() => toggleWeekend(idx)}>{day}</button>
              ))}
            </div>
          </div>

          <div className="date-area">
            <div>
              <div className="mini-title">Public holidays</div>
              <div className="row">
                <input type="date" value={newDate} onChange={(e) => setNewDate(e.target.value)} />
                <button onClick={() => addUnique(newDate, holidays, setHolidays)}>Add</button>
              </div>
              <small>{holidays.length} holidays</small>
            </div>

            <div>
              <div className="mini-title">Pre-booked PTO</div>
              <div className="row">
                <input type="date" value={newDate} onChange={(e) => setNewDate(e.target.value)} />
                <button onClick={() => addUnique(newDate, prebooked, setPrebooked)}>Add</button>
              </div>
              <small>{prebooked.length} pre-booked day(s)</small>
            </div>

            <div>
              <div className="mini-title">Company days off</div>
              <div className="row">
                <input type="date" value={newDate} onChange={(e) => setNewDate(e.target.value)} />
                <button onClick={() => addUnique(newDate, companyDays, setCompanyDays)}>Add</button>
              </div>
              <small>{companyDays.length} company day(s)</small>
            </div>
          </div>

          <div className="btn-row">
            <button onClick={saveScenario}>Save scenario</button>
            <button onClick={exportJson}>Export JSON</button>
          </div>
        </section>

        <section className="panel">
          <h2>Optimized Plan</h2>
          <div className="stats">
            <article><strong>{result.totalDaysOff}</strong><span>Total days off</span></article>
            <article><strong>{result.ptoUsed}</strong><span>PTO used</span></article>
            <article><strong>{result.ptoRemaining}</strong><span>PTO left</span></article>
          </div>

          <div className="calendar-actions">
            <button onClick={exportPlanIcs}>Add all to calendar (.ics)</button>
          </div>

          <div className="break-list">
            {result.breaks.length === 0 && <p className="muted">No break combinations found with the current constraints. Try increasing PTO or changing strategy.</p>}
            {result.breaks.map((b, idx) => {
              const start = parseISO(b.start).toLocaleDateString();
              const end = parseISO(b.end).toLocaleDateString();
              const googleUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(`PTO Break ${idx + 1}`)}&dates=${toIcsDate(b.start)}/${toIcsDate(b.endExclusive)}&details=${encodeURIComponent(`PTO used: ${b.ptoDays.length} days`)}`;
              return (
                <article key={`${b.start}-${b.end}`} className="break-card">
                  <h3>Break #{idx + 1} · {b.daysOff} days off</h3>
                  <p>{start} → {end}</p>
                  <p>PTO days to book: {b.ptoDays.join(', ') || 'None'}</p>
                  <div className="btn-row">
                    <a href={googleUrl} target="_blank" rel="noreferrer">Add to Google</a>
                    <button onClick={() => download(`pto-break-${idx + 1}.ics`, buildIcs(`Break ${idx + 1}`, [b]), 'text/calendar;charset=utf-8')}>Download .ics</button>
                  </div>
                </article>
              );
            })}
          </div>

          <div className="ideas">
            <h3>Feature ideas to enhance further</h3>
            <ul>
              <li>Multi-country holiday packs + one-click compliance calendars.</li>
              <li>Team sync mode to find overlap breaks across colleagues.</li>
              <li>Price-aware travel integration to prioritize low-fare windows.</li>
              <li>Slack/Email reminders for booking deadlines.</li>
            </ul>
          </div>

          <div className="ideas">
            <h3>Saved scenarios (duplication)</h3>
            {scenarioSnapshots.length === 0 && <p className="muted">No saved scenarios yet.</p>}
            {scenarioSnapshots.map((s) => (
              <div key={s.id} className="scenario-row">
                <span>{s.label}</span>
                <button onClick={() => duplicateScenario(s)}>Duplicate + load</button>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
